fullScreen();
color black=#000000, white=#FFFFFF, yellow=#FFEB05, purple=#CA15E3, yellowNight=#FFEB00, purpleNight=#CA159B;
float x=displayWidth*1/4, y=displayHeight*1/4, widthRect=displayWidth*1/2;
float heightRect=displayHeight*1/2;
int thin=displayWidth*1/50, thick=2*thin;
background(black);
stroke(yellowNight);
strokeWeight(thick);
fill(purpleNight);
rect(x, y, widthRect, heightRect);
